# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_vendordetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
        migrations.RenameModel(
            old_name='VendorDetails',
            new_name='VendorDetail',
        ),
    ]
