# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20170629_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='vendor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
