# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20170629_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('order_count', models.IntegerField(default=0)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.VendorDetail')),
            ],
        ),
    ]
