# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_couponcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.MenuItem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.UserDetail')),
            ],
        ),
    ]
