# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
