# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_orderdetail_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='coupon_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
