# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_couponcode_discount_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='item_id',
        ),
    ]
