# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_remove_couponcode_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='cod_availabitity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetail',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
